version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 730335348548.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t kproject .
      - docker tag kproject:latest 730335348548.dkr.ecr.us-east-1.amazonaws.com/kproject:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 730335348548.dkr.ecr.us-east-1.amazonaws.com/kproject:latest
