apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics-app
        image: 730335348548.dkr.ecr.us-east-1.amazonaws.com/kproject:latest
        ports:
        - containerPort: 5000
